version: "3.8"

services:
  mongoDB:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: deliveryDB
    ports:
      - "27018:27017"
    volumes:
      - ./delivery-service/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always
    container_name: deliveryDB

  mysql:
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=juanse
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=ecommerceDB
    container_name: ecommerceDB
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=ecommerceDB
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: adminDatabase

  delivery-service:
    build: ./delivery-service
    image: delivery-service
    depends_on:
      - mongoDB
    environment:
      PORT: "3000"
      DB_URL: "mongodb://admin:admin@deliveryDB:27017/deliveryDB"
    ports:
      - "3001:3000"
    volumes:
      - ./delivery-service/:/usr/src
      - ./delivery-service/node_modules:/usr/src/node_modules
    container_name: "delivery-service"
    restart: always
    command: npx nodemon --legacy-watch main.js

  ecommerce-service:
    build: ./ecommerce-service
    image: ecommerce-service
    depends_on:
      - mysql
    environment:
      PORT: "3000"
      DB_USERNAME: "juanse"
      DB_PASSWORD: "admin"
      DB_DATABASE: "ecommerceDB"
      DB_HOST: "ecommerceDB"
      CSR_NUMBER: "10"
      SECRETKEY: "85GplflN9lICjxnuDXOM"
    ports:
      - "3000:3000"
    volumes:
      - ./ecommerce-service/:/usr/src
      - ./ecommerce-service/node_modules:/usr/src/node_modules
    container_name: "ecommerce-service"
    restart: always
    command: npx nodemon --legacy-watch main.js
